### ISSUE TITLE
Sharing a link to /predict results in a “method not allowed” error

### ISSUE THREAD

**Issue by ticky** [mathemakitten/bad-wolfram-alpha#2]
If a user shares a link based on the results page, the server returns a “method not allowed” as the `/predict` route doesn’t accept or handle GET requests.

It would be better if requests like this redirected to the home page instead, as that’s more likely to be what the user is after!

**Comment by mathemakitten** [comment]
Thanks! I noticed this too. Can you recommend a good way to do this? I'm not super familiar with best practices around web redirects (I'm pretty new to web dev!)

**Comment by ticky** [comment]
Thanks for reminding me, I had meant to get to contributing this but didn’t have a moment at the time. I’ve put together #5 for you!
